name: prophecy-pbt-repo-test
description: ''
version: 0.0.1
author: maciej@prophecy.io
language: python
buildSystem: wheel
pipelines:
  pipelines/test-pipeline:
    name: test-pipeline
    description: ''
    author: maciej@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-08-24 11:46:18'
    datasets:
      inputs:
      - 2867/datasets/customers-source
      outputs:
      - 2867/datasets/customers-output
    dependencies: {}
datasets:
  datasets/customers-output:
    name: customers-output
    description: ''
    author: maciej@prophecy.io
    createdAt: '2022-08-24 11:47:28'
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: maciej@prophecy.io
        createdAt: '2022-08-24 11:47:28'
  datasets/customers-source:
    name: customers-source
    description: ''
    author: maciej@prophecy.io
    createdAt: '2022-08-24 11:55:25'
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: maciej@prophecy.io
        createdAt: '2022-08-24 11:55:25'
templates: {}
jobs:
  jobs/schedule-test:
    name: schedule-test
    description: ''
    fabricUID: 2
    scheduler:
      Databricks: {}
    jobSize: Small
    scheduleCron: 0 0 0/1 * * ? *
    timeout: null
    alerting:
      emails: maciej@prophecy.io
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - 2867/pipelines/test-pipeline
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2022-08-24 11:59:05'
    author: maciej@prophecy.io
libraries: []
subgraphs: {}
dependencies: '[]'
